from ..models import DivineBeing

# Add angels to the system
angels = [
    DivineBeing(
        name="Metatron",
        sephirah="Kether",
        qualities=["divine light", "unity"],
        domains=["divine light", "unity"],
        invocation_message="Guide us with your divine light, illuminate our path with the unity of the cosmos.",
        lunar_essence="The blinding light of the cosmic moon",
        celestial_body="Sun",
        sphere_of_influence="Divine presence and cosmic order",
    ),
    DivineBeing(
        name="Raziel",
        sephirah="Chokmah",
        qualities=["wisdom", "creative force"],
        domains=["wisdom", "knowledge"],
        invocation_message="Guide us with your profound wisdom, illuminate our minds with your creative force.",
        lunar_essence="The radiant glow of the wise moon",
        celestial_body="Uranus",
        sphere_of_influence="Wisdom and secrets of the universe",
    ),
    DivineBeing(
        name="Tzaphkiel",
        sephirah="Binah",
        qualities=["understanding", "form"],
        domains=["understanding", "insight"],
        invocation_message="Guide us with your deep understanding, illuminate our lives with the clarity of your insight.",
        lunar_essence="The deep mystery of the new moon",
        celestial_body="Saturn",
        sphere_of_influence="Structure and understanding",
    ),
    DivineBeing(
        name="Tzadkiel",
        sephirah="Chesed",
        qualities=["mercy", "expansion"],
        domains=["mercy", "benevolence"],
        invocation_message="Guide us with your endless mercy, illuminate our paths with your benevolent light.",
        lunar_essence="The soft glow of the gibbous moon",
        celestial_body="Jupiter",
        sphere_of_influence="Expansion and benevolence",
    ),
    DivineBeing(
        name="Samael",
        sephirah="Geburah",
        qualities=["strength", "discipline"],
        domains=["strength", "justice"],
        invocation_message="Guide us with your fierce strength, illuminate our lives with the power of discipline.",
        lunar_essence="The intense power of the blood moon",
        celestial_body="Mars",
        sphere_of_influence="Strength and discipline",
    ),
    DivineBeing(
        name="Raphael",
        sephirah="Tiphereth",
        qualities=["beauty", "harmony"],
        domains=["healing", "beauty"],
        invocation_message="Guide us with your healing touch, illuminate our souls with the harmony of beauty.",
        lunar_essence="The warm glow of the harvest moon",
        celestial_body="Sun",
        sphere_of_influence="Healing and harmony",
    ),
    DivineBeing(
        name="Haniel",
        sephirah="Netzach",
        qualities=["victory", "endurance"],
        domains=["victory", "love"],
        invocation_message="Guide us with your victorious spirit, illuminate our hearts with your enduring love.",
        lunar_essence="The gentle radiance of the crescent moon",
        celestial_body="Venus",
        sphere_of_influence="Love and victory",
    ),
    DivineBeing(
        name="Michael",
        sephirah="Hod",
        qualities=["glory", "splendor"],
        domains=["protection", "glory"],
        invocation_message="Guide us with your protective presence, illuminate our paths with your glorious light.",
        lunar_essence="The shadowy luminescence of the dark moon",
        celestial_body="Mercury",
        sphere_of_influence="Protection and glory",
    ),
    DivineBeing(
        name="Gabriel",
        sephirah="Yesod",
        qualities=["foundation", "connection to the divine"],
        domains=["communication", "foundation"],
        invocation_message="Guide us with your divine communication, illuminate our spirits with your foundational strength.",
        lunar_essence="The ethereal glow of the full moon",
        celestial_body="Moon",
        sphere_of_influence="Divine connection and communication",
    ),
    DivineBeing(
        name="Sandalphon",
        sephirah="Malkuth",
        qualities=["manifestation", "earthly presence"],
        domains=["manifestation", "earth"],
        invocation_message="Guide us with your grounded presence, illuminate our paths with the light of manifestation.",
        lunar_essence="The fertile glow of the earth's moon",
        celestial_body="Earth",
        sphere_of_influence="Manifestation and earthly presence",
    ),
]
